name: Master Branch

on:
  push:
    branches:
      - 'master'
      - 'frontend'
jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Maven Package
        run: mvn -B clean package -DskipTests -Dskip.frontend=true
      - name: Maven Verify
        run: mvn -B clean verify -Dskip.frontend=true

  frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.0"
        run: sh ./build_frontend.sh

  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}