name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'

jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven Package
        run: ./mvnw -B clean package -DskipTests -Dskip.frontend=true
      - name: Maven Verify
        run: ./mvnw -B clean verify -Dskip.frontend=true
      - uses: codecov/codecov-action@v2
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests